occipital coordinates: [15, -98, 0]
analyses:
  ssvep:
    variables: ["SNR", "amplitude"]
    continuous:
      volumes: [1, 2, 3, 4, 5, 6, 7, 8]
    trialwise:
      volumes: ["na"]
  alpha:
    continuous:
      volumes: [1, 2, 3, 4]
      variables: ["SNR", "amplitude"]
    trialwise:
      volumes: ["na"]
      variables: ["amplitude"]
