occipital coordinates: [15, -98, 0]
analyses:
  ssvep:
    continuous:
      volumes: [1, 2, 3, 4, 5, 6, 7, 8]
      variables: ["SNR", "amplitude"]
      compare to baseline: ["false"]
    trialwise:
      volumes: ["na"]
      variables: ["SNR", "amplitude"]
      compare to baseline: ["false"]
  alpha:
    continuous:
      volumes: [1, 2, 3, 4]
      variables: ["SNR", "amplitude"]
      compare to baseline: ["false"]
    trialwise:
      volumes: ["na"]
      variables: ["amplitude"]
      compare to baseline: ["false"]


thresholds:
  ssvep:
    "97.5":
      [-0.066, 0.063]
    "95":
      [-0.064, 0.062]
  alpha:
    "97.5":
      [-0.063, 0.066]
    "95":
      [-0.062, 0.063]
