from snakemake.utils import min_version

min_version("6.4.1")


configfile: "config/config.yaml"


report: "report/workflow.rst"


container: "continuumio/miniconda3"


include: "rules/plot_mean_correlations.smk"


rule all:
    input:
        expand("results/plots/startvolume-{startvolume}.png", startvolume=config["trim alpha volumes"])
